' Generated by VB.NET Class Generator

Imports WMS_STD_Formula
Imports WMS_STD_Formula.W_Module
Imports System.Data
Imports System.Data.SqlClient

Public Class svar_TransportManifestCharge : Inherits DBType_SQLServer

#Region "Declarations"
    Private _dataTable As DataTable = New DataTable
    Private _scalarOutput As String

    Private _running As Integer
    Private _customer_index As String
    Private _TransportManifest_Index As String
    Private _transportregion_index As String
    Private _carrier_index As String
    Private _description As String
    Private _sum_drop As Double
    Private _total_qty As Double
    Private _weight As Double
    Private _volume As Double
    Private _amount As Double
    Private _amount_charge As Double
    Private _Minimum_Rate As Double
    Private _transportcharge_type As Integer
    Private _found As Boolean

#End Region

    Public ReadOnly Property DataTable() As DataTable
        Get
            Return _dataTable
        End Get
    End Property
    Public ReadOnly Property ScalarOutput() As String
        Get
            Return _scalarOutput
        End Get
    End Property

#Region "Properties"

    Public Property Running() As Integer
        Get
            Return _running
        End Get
        Set(ByVal Value As Integer)
            _running = Value
        End Set
    End Property
    Public Property TransportManifest_Index() As String
        Get
            Return _TransportManifest_Index
        End Get
        Set(ByVal Value As String)
            _TransportManifest_Index = Value
        End Set
    End Property
    Public Property Customer_Index() As String
        Get
            Return _customer_index
        End Get
        Set(ByVal Value As String)
            _customer_index = Value
        End Set
    End Property

    Public Property TransportRegion_Index() As String
        Get
            Return _transportregion_index
        End Get
        Set(ByVal Value As String)
            _transportregion_index = Value
        End Set
    End Property

    Public Property Carrier_Index() As String
        Get
            Return _carrier_index
        End Get
        Set(ByVal Value As String)
            _carrier_index = Value
        End Set
    End Property

    Public Property [Description]() As String
        Get
            Return _description
        End Get
        Set(ByVal Value As String)
            _description = Value
        End Set
    End Property

    Public Property sumDrop() As Double
        Get
            Return _sum_drop
        End Get
        Set(ByVal Value As Double)
            _sum_drop = Value
        End Set
    End Property

    Public Property Total_Qty() As Double
        Get
            Return _total_qty
        End Get
        Set(ByVal Value As Double)
            _total_qty = Value
        End Set
    End Property

    Public Property Weight() As Double
        Get
            Return _weight
        End Get
        Set(ByVal Value As Double)
            _weight = Value
        End Set
    End Property

    Public Property Volume() As Double
        Get
            Return _volume
        End Get
        Set(ByVal Value As Double)
            _volume = Value
        End Set
    End Property

    Public Property Amount() As Double
        Get
            Return _amount
        End Get
        Set(ByVal Value As Double)
            _amount = Value
        End Set
    End Property

    Public Property Amount_Charge() As Double
        Get
            Return _amount_charge
        End Get
        Set(ByVal Value As Double)
            _amount_charge = Value
        End Set
    End Property
    Public Property Minimum_Rate() As Double
        Get
            Return _Minimum_Rate
        End Get
        Set(ByVal Value As Double)
            _Minimum_Rate = Value
        End Set
    End Property
    Public Property TransportCharge_Type() As Integer
        Get
            Return _transportcharge_type
        End Get
        Set(ByVal Value As Integer)
            _transportcharge_type = Value
        End Set
    End Property

    Public ReadOnly Property Found() As Boolean
        Get
            Return _found
        End Get
    End Property

#End Region

    Public Sub getTransportManifestCharge(ByVal TransportCharge_Type As Integer, ByVal TransportManifest_Index As String)
        Dim strSQL As String = ""
        Try
            strSQL = "  SELECT  * "
            strSQL &= " FROM    VIEW_TransportManifestCharge "
            strSQL &= " WHERE   TransportCharge_Type = " & TransportCharge_Type
            strSQL &= "     AND TransportManifest_Index = '" & TransportManifest_Index & "'"
            SetSQLString = strSQL
            connectDB()
            EXEC_DataAdapter()
            _dataTable = GetDataTable
        Catch ex As Exception
            Throw ex
        Finally
            disconnectDB()
        End Try
    End Sub


End Class
