'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8937
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WMS_Site_Topcharoen_Interface.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Emptys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emptys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property เพิ่มรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เพิ่มรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property เลือกรายการ___เลือก() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เลือกรายการ___เลือก", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แก้ไขรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แก้ไขรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แนะนำตำแหน่งจัดเก็บ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แนะนำตำแหน่งจัดเก็บ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แนะนำตำแหน่งจัดเก็บ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แนะนำตำแหน่งจัดเก็บ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แนะนำตำแหน่งจัดเก็บ2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แนะนำตำแหน่งจัดเก็บ2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แสดงรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แสดงรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แสดงรายการ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แสดงรายการ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แสดงรายการ2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แสดงรายการ2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ค้นหา() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ค้นหา", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ดึงข้อมูล() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ดึงข้อมูล", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ยกเลิกรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ยกเลิกรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ยืนยันรายการ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ยืนยันรายการ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property รายงาน_แสดงรายงาน() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("รายงาน_แสดงรายงาน", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ลบรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ลบรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ล้างหน้าจอ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ล้างหน้าจอ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ล้างหน้าจอ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ล้างหน้าจอ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ส่งข้อมูล() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ส่งข้อมูล", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ออกจากระบบ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ออกจากระบบ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ออกจากระบบ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ออกจากระบบ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ออกจากระบบ2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ออกจากระบบ2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
