'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8833
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WMS_Site_TopCharoen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _100_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _100_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_100_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_25_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_25_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_100_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_100_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_25_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_25_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_75_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_75_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_blue_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_blue_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_found() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_found", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_resv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_resv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2d_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2d_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_100_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_100_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_25_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_25_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_50_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_50_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_75() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_75", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_75_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_75_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_found() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_found", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_resv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_resv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2dbt_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2dbt_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _50_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _50_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_50_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _75_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_75_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _75_roll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_75_roll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alignbottoms1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alignbottoms1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alignlefts1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alignlefts1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alignrights1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alignrights1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aligntops1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aligntops1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property area() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("area", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_clean_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background_clean_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar_graph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar_graph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barcode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box5edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box5edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property box5temp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box5temp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calculator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calculator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ColorGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property communitylogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("communitylogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DotNetNuke() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DotNetNuke", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Emptys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emptys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ForkLift() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ForkLift", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kascologo42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kascologo42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line_graph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line_graph", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Matrix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Matrix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pinned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pinned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rack1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rack1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RACKTYPE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RACKTYPE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RACKTYPE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RACKTYPE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RACKTYPE3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RACKTYPE3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RACKTYPE4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RACKTYPE4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RACKTYPE5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RACKTYPE5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reserved() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reserved", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rhs1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rhs1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property same_height() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("same_height", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property same_size() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("same_size", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property same_width() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("same_width", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sidebox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sidebox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property single_cube() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("single_cube", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_blue_v() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_blue_v", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_empty_v() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_empty_v", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_empty1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_empty1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_found() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_found", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_resv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_resv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property top_used_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top_used_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topfullbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topfullbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_blocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_found() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_found", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_resv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_resv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property topv_used_full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topv_used_full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property truck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unpinned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unpinned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wmsbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wmsbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property เพิ่มรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เพิ่มรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property เลือกรายการ___เลือก() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("เลือกรายการ___เลือก", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แก้ไขรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แก้ไขรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property แนะนำตำแหน่งจัดเก็บ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("แนะนำตำแหน่งจัดเก็บ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ค้นหา() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ค้นหา", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ดึงข้อมูล() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ดึงข้อมูล", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ยกเลิกรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ยกเลิกรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ยืนยันรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ยืนยันรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property รายงาน_แสดงรายงาน() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("รายงาน_แสดงรายงาน", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ลบรายการ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ลบรายการ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ล้างหน้าจอ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ล้างหน้าจอ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ล้างหน้าจอ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ล้างหน้าจอ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ส่งข้อมูล() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ส่งข้อมูล", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ออกจากระบบ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ออกจากระบบ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
