'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8833
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsSummary_Consolidate_Shipment"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsSummary_Consolidate_Shipment
    Inherits Global.System.Data.DataSet
    
    Private tableVIEW_RPT_Summary_Consolidate_Shipment As VIEW_RPT_Summary_Consolidate_ShipmentDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("VIEW_RPT_Summary_Consolidate_Shipment")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_RPT_Summary_Consolidate_ShipmentDataTable(ds.Tables("VIEW_RPT_Summary_Consolidate_Shipment")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property VIEW_RPT_Summary_Consolidate_Shipment() As VIEW_RPT_Summary_Consolidate_ShipmentDataTable
        Get
            Return Me.tableVIEW_RPT_Summary_Consolidate_Shipment
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsSummary_Consolidate_Shipment = CType(MyBase.Clone,dsSummary_Consolidate_Shipment)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("VIEW_RPT_Summary_Consolidate_Shipment")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_RPT_Summary_Consolidate_ShipmentDataTable(ds.Tables("VIEW_RPT_Summary_Consolidate_Shipment")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableVIEW_RPT_Summary_Consolidate_Shipment = CType(MyBase.Tables("VIEW_RPT_Summary_Consolidate_Shipment"),VIEW_RPT_Summary_Consolidate_ShipmentDataTable)
        If (initTable = true) Then
            If (Not (Me.tableVIEW_RPT_Summary_Consolidate_Shipment) Is Nothing) Then
                Me.tableVIEW_RPT_Summary_Consolidate_Shipment.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsSummary_Consolidate_Shipment"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsSummary_Consolidate_Shipment.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableVIEW_RPT_Summary_Consolidate_Shipment = New VIEW_RPT_Summary_Consolidate_ShipmentDataTable
        MyBase.Tables.Add(Me.tableVIEW_RPT_Summary_Consolidate_Shipment)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeVIEW_RPT_Summary_Consolidate_Shipment() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsSummary_Consolidate_Shipment = New dsSummary_Consolidate_Shipment
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEventHandler(ByVal sender As Object, ByVal e As VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class VIEW_RPT_Summary_Consolidate_ShipmentDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnShipment_No As Global.System.Data.DataColumn
        
        Private columnRoute_Desc As Global.System.Data.DataColumn
        
        Private columnCustomer_Shipping_Desc As Global.System.Data.DataColumn
        
        Private columnSO As Global.System.Data.DataColumn
        
        Private columnSku_Id As Global.System.Data.DataColumn
        
        Private columnEAN As Global.System.Data.DataColumn
        
        Private columnSku_Desc As Global.System.Data.DataColumn
        
        Private columnOrder_Qty As Global.System.Data.DataColumn
        
        Private columnOpen_Qty As Global.System.Data.DataColumn
        
        Private columnPackage_Desc As Global.System.Data.DataColumn
        
        Private columnNotes As Global.System.Data.DataColumn
        
        Private columnWeight As Global.System.Data.DataColumn
        
        Private columnadd_by As Global.System.Data.DataColumn
        
        Private columnDriver_name As Global.System.Data.DataColumn
        
        Private columnDriver_lastname As Global.System.Data.DataColumn
        
        Private columnShipToName As Global.System.Data.DataColumn
        
        Private columnNumberSO As Global.System.Data.DataColumn
        
        Private columnCustomer_Shipping_Id As Global.System.Data.DataColumn
        
        Private columnQty_Bal As Global.System.Data.DataColumn
        
        Private columnPackageSku_Desc As Global.System.Data.DataColumn
        
        Private columnWeight_G As Global.System.Data.DataColumn
        
        Private columnTransportRegion_Desc As Global.System.Data.DataColumn
        
        Private columnSubRoute_Desc As Global.System.Data.DataColumn
        
        Private columnDistributionCenter_Desc As Global.System.Data.DataColumn
        
        Private columnShipment_Date As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "VIEW_RPT_Summary_Consolidate_Shipment"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Shipment_NoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShipment_No
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Route_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRoute_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Customer_Shipping_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCustomer_Shipping_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Sku_IdColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSku_Id
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property EANColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEAN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Sku_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSku_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Order_QtyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOrder_Qty
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Open_QtyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnOpen_Qty
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Package_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPackage_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NotesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNotes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property WeightColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnWeight
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property add_byColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnadd_by
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Driver_nameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDriver_name
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Driver_lastnameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDriver_lastname
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ShipToNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShipToName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property NumberSOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNumberSO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Customer_Shipping_IdColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCustomer_Shipping_Id
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Qty_BalColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnQty_Bal
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PackageSku_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPackageSku_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Weight_GColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnWeight_G
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TransportRegion_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTransportRegion_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SubRoute_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSubRoute_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DistributionCenter_DescColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistributionCenter_Desc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Shipment_DateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShipment_Date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As VIEW_RPT_Summary_Consolidate_ShipmentRow
            Get
                Return CType(Me.Rows(index),VIEW_RPT_Summary_Consolidate_ShipmentRow)
            End Get
        End Property
        
        Public Event VIEW_RPT_Summary_Consolidate_ShipmentRowChanging As VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEventHandler
        
        Public Event VIEW_RPT_Summary_Consolidate_ShipmentRowChanged As VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEventHandler
        
        Public Event VIEW_RPT_Summary_Consolidate_ShipmentRowDeleting As VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEventHandler
        
        Public Event VIEW_RPT_Summary_Consolidate_ShipmentRowDeleted As VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddVIEW_RPT_Summary_Consolidate_ShipmentRow(ByVal row As VIEW_RPT_Summary_Consolidate_ShipmentRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddVIEW_RPT_Summary_Consolidate_ShipmentRow( _
                    ByVal Shipment_No As String,  _
                    ByVal Route_Desc As String,  _
                    ByVal Customer_Shipping_Desc As String,  _
                    ByVal SO As String,  _
                    ByVal Sku_Id As String,  _
                    ByVal EAN As String,  _
                    ByVal Sku_Desc As String,  _
                    ByVal Order_Qty As Double,  _
                    ByVal Open_Qty As Double,  _
                    ByVal Package_Desc As String,  _
                    ByVal Notes As String,  _
                    ByVal Weight As Double,  _
                    ByVal add_by As String,  _
                    ByVal Driver_name As String,  _
                    ByVal Driver_lastname As String,  _
                    ByVal ShipToName As String,  _
                    ByVal NumberSO As String,  _
                    ByVal Customer_Shipping_Id As String,  _
                    ByVal Qty_Bal As Double,  _
                    ByVal PackageSku_Desc As String,  _
                    ByVal Weight_G As Double,  _
                    ByVal TransportRegion_Desc As String,  _
                    ByVal SubRoute_Desc As String,  _
                    ByVal DistributionCenter_Desc As String,  _
                    ByVal Shipment_Date As Date) As VIEW_RPT_Summary_Consolidate_ShipmentRow
            Dim rowVIEW_RPT_Summary_Consolidate_ShipmentRow As VIEW_RPT_Summary_Consolidate_ShipmentRow = CType(Me.NewRow,VIEW_RPT_Summary_Consolidate_ShipmentRow)
            Dim columnValuesArray() As Object = New Object() {Shipment_No, Route_Desc, Customer_Shipping_Desc, SO, Sku_Id, EAN, Sku_Desc, Order_Qty, Open_Qty, Package_Desc, Notes, Weight, add_by, Driver_name, Driver_lastname, ShipToName, NumberSO, Customer_Shipping_Id, Qty_Bal, PackageSku_Desc, Weight_G, TransportRegion_Desc, SubRoute_Desc, DistributionCenter_Desc, Shipment_Date}
            rowVIEW_RPT_Summary_Consolidate_ShipmentRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowVIEW_RPT_Summary_Consolidate_ShipmentRow)
            Return rowVIEW_RPT_Summary_Consolidate_ShipmentRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As VIEW_RPT_Summary_Consolidate_ShipmentDataTable = CType(MyBase.Clone,VIEW_RPT_Summary_Consolidate_ShipmentDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New VIEW_RPT_Summary_Consolidate_ShipmentDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnShipment_No = MyBase.Columns("Shipment_No")
            Me.columnRoute_Desc = MyBase.Columns("Route_Desc")
            Me.columnCustomer_Shipping_Desc = MyBase.Columns("Customer_Shipping_Desc")
            Me.columnSO = MyBase.Columns("SO")
            Me.columnSku_Id = MyBase.Columns("Sku_Id")
            Me.columnEAN = MyBase.Columns("EAN")
            Me.columnSku_Desc = MyBase.Columns("Sku_Desc")
            Me.columnOrder_Qty = MyBase.Columns("Order_Qty")
            Me.columnOpen_Qty = MyBase.Columns("Open_Qty")
            Me.columnPackage_Desc = MyBase.Columns("Package_Desc")
            Me.columnNotes = MyBase.Columns("Notes")
            Me.columnWeight = MyBase.Columns("Weight")
            Me.columnadd_by = MyBase.Columns("add_by")
            Me.columnDriver_name = MyBase.Columns("Driver_name")
            Me.columnDriver_lastname = MyBase.Columns("Driver_lastname")
            Me.columnShipToName = MyBase.Columns("ShipToName")
            Me.columnNumberSO = MyBase.Columns("NumberSO")
            Me.columnCustomer_Shipping_Id = MyBase.Columns("Customer_Shipping_Id")
            Me.columnQty_Bal = MyBase.Columns("Qty_Bal")
            Me.columnPackageSku_Desc = MyBase.Columns("PackageSku_Desc")
            Me.columnWeight_G = MyBase.Columns("Weight_G")
            Me.columnTransportRegion_Desc = MyBase.Columns("TransportRegion_Desc")
            Me.columnSubRoute_Desc = MyBase.Columns("SubRoute_Desc")
            Me.columnDistributionCenter_Desc = MyBase.Columns("DistributionCenter_Desc")
            Me.columnShipment_Date = MyBase.Columns("Shipment_Date")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnShipment_No = New Global.System.Data.DataColumn("Shipment_No", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShipment_No)
            Me.columnRoute_Desc = New Global.System.Data.DataColumn("Route_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRoute_Desc)
            Me.columnCustomer_Shipping_Desc = New Global.System.Data.DataColumn("Customer_Shipping_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCustomer_Shipping_Desc)
            Me.columnSO = New Global.System.Data.DataColumn("SO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSO)
            Me.columnSku_Id = New Global.System.Data.DataColumn("Sku_Id", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSku_Id)
            Me.columnEAN = New Global.System.Data.DataColumn("EAN", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEAN)
            Me.columnSku_Desc = New Global.System.Data.DataColumn("Sku_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSku_Desc)
            Me.columnOrder_Qty = New Global.System.Data.DataColumn("Order_Qty", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOrder_Qty)
            Me.columnOpen_Qty = New Global.System.Data.DataColumn("Open_Qty", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnOpen_Qty)
            Me.columnPackage_Desc = New Global.System.Data.DataColumn("Package_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPackage_Desc)
            Me.columnNotes = New Global.System.Data.DataColumn("Notes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNotes)
            Me.columnWeight = New Global.System.Data.DataColumn("Weight", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnWeight)
            Me.columnadd_by = New Global.System.Data.DataColumn("add_by", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnadd_by)
            Me.columnDriver_name = New Global.System.Data.DataColumn("Driver_name", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDriver_name)
            Me.columnDriver_lastname = New Global.System.Data.DataColumn("Driver_lastname", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDriver_lastname)
            Me.columnShipToName = New Global.System.Data.DataColumn("ShipToName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShipToName)
            Me.columnNumberSO = New Global.System.Data.DataColumn("NumberSO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNumberSO)
            Me.columnCustomer_Shipping_Id = New Global.System.Data.DataColumn("Customer_Shipping_Id", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCustomer_Shipping_Id)
            Me.columnQty_Bal = New Global.System.Data.DataColumn("Qty_Bal", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQty_Bal)
            Me.columnPackageSku_Desc = New Global.System.Data.DataColumn("PackageSku_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPackageSku_Desc)
            Me.columnWeight_G = New Global.System.Data.DataColumn("Weight_G", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnWeight_G)
            Me.columnTransportRegion_Desc = New Global.System.Data.DataColumn("TransportRegion_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTransportRegion_Desc)
            Me.columnSubRoute_Desc = New Global.System.Data.DataColumn("SubRoute_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSubRoute_Desc)
            Me.columnDistributionCenter_Desc = New Global.System.Data.DataColumn("DistributionCenter_Desc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistributionCenter_Desc)
            Me.columnShipment_Date = New Global.System.Data.DataColumn("Shipment_Date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShipment_Date)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewVIEW_RPT_Summary_Consolidate_ShipmentRow() As VIEW_RPT_Summary_Consolidate_ShipmentRow
            Return CType(Me.NewRow,VIEW_RPT_Summary_Consolidate_ShipmentRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New VIEW_RPT_Summary_Consolidate_ShipmentRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(VIEW_RPT_Summary_Consolidate_ShipmentRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.VIEW_RPT_Summary_Consolidate_ShipmentRowChangedEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_Summary_Consolidate_ShipmentRowChanged(Me, New VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent(CType(e.Row,VIEW_RPT_Summary_Consolidate_ShipmentRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.VIEW_RPT_Summary_Consolidate_ShipmentRowChangingEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_Summary_Consolidate_ShipmentRowChanging(Me, New VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent(CType(e.Row,VIEW_RPT_Summary_Consolidate_ShipmentRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.VIEW_RPT_Summary_Consolidate_ShipmentRowDeletedEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_Summary_Consolidate_ShipmentRowDeleted(Me, New VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent(CType(e.Row,VIEW_RPT_Summary_Consolidate_ShipmentRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.VIEW_RPT_Summary_Consolidate_ShipmentRowDeletingEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_Summary_Consolidate_ShipmentRowDeleting(Me, New VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent(CType(e.Row,VIEW_RPT_Summary_Consolidate_ShipmentRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveVIEW_RPT_Summary_Consolidate_ShipmentRow(ByVal row As VIEW_RPT_Summary_Consolidate_ShipmentRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsSummary_Consolidate_Shipment = New dsSummary_Consolidate_Shipment
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "VIEW_RPT_Summary_Consolidate_ShipmentDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class VIEW_RPT_Summary_Consolidate_ShipmentRow
        Inherits Global.System.Data.DataRow
        
        Private tableVIEW_RPT_Summary_Consolidate_Shipment As VIEW_RPT_Summary_Consolidate_ShipmentDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableVIEW_RPT_Summary_Consolidate_Shipment = CType(Me.Table,VIEW_RPT_Summary_Consolidate_ShipmentDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Shipment_No() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_NoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Shipment_No' in table 'VIEW_RPT_Summary_Consolidate_Shipmen"& _ 
                            "t' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_NoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Route_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Route_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Route_Desc' in table 'VIEW_RPT_Summary_Consolidate_Shipment"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Route_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Customer_Shipping_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Customer_Shipping_Desc' in table 'VIEW_RPT_Summary_Consolid"& _ 
                            "ate_Shipment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SO' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sku_Id() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_IdColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Sku_Id' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is"& _ 
                            " DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_IdColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property EAN() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.EANColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'EAN' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.EANColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sku_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Sku_Desc' in table 'VIEW_RPT_Summary_Consolidate_Shipment' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Order_Qty() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Order_QtyColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Order_Qty' in table 'VIEW_RPT_Summary_Consolidate_Shipment'"& _ 
                            " is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Order_QtyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Open_Qty() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Open_QtyColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Open_Qty' in table 'VIEW_RPT_Summary_Consolidate_Shipment' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Open_QtyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Package_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Package_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Package_Desc' in table 'VIEW_RPT_Summary_Consolidate_Shipme"& _ 
                            "nt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Package_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Notes() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NotesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Notes' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NotesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Weight() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.WeightColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Weight' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is"& _ 
                            " DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.WeightColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property add_by() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.add_byColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'add_by' in table 'VIEW_RPT_Summary_Consolidate_Shipment' is"& _ 
                            " DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.add_byColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Driver_name() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_nameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Driver_name' in table 'VIEW_RPT_Summary_Consolidate_Shipmen"& _ 
                            "t' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_nameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Driver_lastname() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_lastnameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Driver_lastname' in table 'VIEW_RPT_Summary_Consolidate_Shi"& _ 
                            "pment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_lastnameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ShipToName() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.ShipToNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ShipToName' in table 'VIEW_RPT_Summary_Consolidate_Shipment"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.ShipToNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property NumberSO() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NumberSOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NumberSO' in table 'VIEW_RPT_Summary_Consolidate_Shipment' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NumberSOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Customer_Shipping_Id() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_IdColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Customer_Shipping_Id' in table 'VIEW_RPT_Summary_Consolidat"& _ 
                            "e_Shipment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_IdColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qty_Bal() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Qty_BalColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Qty_Bal' in table 'VIEW_RPT_Summary_Consolidate_Shipment' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Qty_BalColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PackageSku_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.PackageSku_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PackageSku_Desc' in table 'VIEW_RPT_Summary_Consolidate_Shi"& _ 
                            "pment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.PackageSku_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Weight_G() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Weight_GColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Weight_G' in table 'VIEW_RPT_Summary_Consolidate_Shipment' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Weight_GColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TransportRegion_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.TransportRegion_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TransportRegion_Desc' in table 'VIEW_RPT_Summary_Consolidat"& _ 
                            "e_Shipment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.TransportRegion_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SubRoute_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SubRoute_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SubRoute_Desc' in table 'VIEW_RPT_Summary_Consolidate_Shipm"& _ 
                            "ent' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SubRoute_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DistributionCenter_Desc() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.DistributionCenter_DescColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DistributionCenter_Desc' in table 'VIEW_RPT_Summary_Consoli"& _ 
                            "date_Shipment' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.DistributionCenter_DescColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Shipment_Date() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_DateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Shipment_Date' in table 'VIEW_RPT_Summary_Consolidate_Shipm"& _ 
                            "ent' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_DateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShipment_NoNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_NoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShipment_NoNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_NoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsRoute_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Route_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetRoute_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Route_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCustomer_Shipping_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCustomer_Shipping_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSONull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSONull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSku_IdNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_IdColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSku_IdNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_IdColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsEANNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.EANColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetEANNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.EANColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSku_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSku_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Sku_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsOrder_QtyNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Order_QtyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetOrder_QtyNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Order_QtyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsOpen_QtyNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Open_QtyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetOpen_QtyNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Open_QtyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPackage_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Package_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPackage_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Package_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNotesNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NotesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNotesNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NotesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsWeightNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.WeightColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetWeightNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.WeightColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isadd_byNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.add_byColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setadd_byNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.add_byColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDriver_nameNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_nameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDriver_nameNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_nameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDriver_lastnameNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_lastnameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDriver_lastnameNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Driver_lastnameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShipToNameNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.ShipToNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShipToNameNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.ShipToNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsNumberSONull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NumberSOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetNumberSONull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.NumberSOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCustomer_Shipping_IdNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_IdColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCustomer_Shipping_IdNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Customer_Shipping_IdColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQty_BalNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Qty_BalColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQty_BalNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Qty_BalColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPackageSku_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.PackageSku_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPackageSku_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.PackageSku_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsWeight_GNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Weight_GColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetWeight_GNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Weight_GColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTransportRegion_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.TransportRegion_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTransportRegion_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.TransportRegion_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSubRoute_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SubRoute_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSubRoute_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.SubRoute_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDistributionCenter_DescNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.DistributionCenter_DescColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDistributionCenter_DescNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.DistributionCenter_DescColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShipment_DateNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_DateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShipment_DateNull()
            Me(Me.tableVIEW_RPT_Summary_Consolidate_Shipment.Shipment_DateColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class VIEW_RPT_Summary_Consolidate_ShipmentRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As VIEW_RPT_Summary_Consolidate_ShipmentRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As VIEW_RPT_Summary_Consolidate_ShipmentRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As VIEW_RPT_Summary_Consolidate_ShipmentRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
