'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8937
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsGoodsIssue_Delivery_Confirmation"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsGoodsIssue_Delivery_Confirmation
    Inherits Global.System.Data.DataSet
    
    Private tableVIEW_RPT_GoodsIssue_Delivery_Confirmation As VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("VIEW_RPT_GoodsIssue_Delivery_Confirmation")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable(ds.Tables("VIEW_RPT_GoodsIssue_Delivery_Confirmation")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property VIEW_RPT_GoodsIssue_Delivery_Confirmation() As VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
        Get
            Return Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsGoodsIssue_Delivery_Confirmation = CType(MyBase.Clone,dsGoodsIssue_Delivery_Confirmation)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("VIEW_RPT_GoodsIssue_Delivery_Confirmation")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable(ds.Tables("VIEW_RPT_GoodsIssue_Delivery_Confirmation")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation = CType(MyBase.Tables("VIEW_RPT_GoodsIssue_Delivery_Confirmation"),VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable)
        If (initTable = true) Then
            If (Not (Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation) Is Nothing) Then
                Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsGoodsIssue_Delivery_Confirmation"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsGoodsIssue_Delivery_Confirmation.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation = New VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
        MyBase.Tables.Add(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeVIEW_RPT_GoodsIssue_Delivery_Confirmation() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsGoodsIssue_Delivery_Confirmation = New dsGoodsIssue_Delivery_Confirmation
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEventHandler(ByVal sender As Object, ByVal e As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnTransportManifest_Index As Global.System.Data.DataColumn
        
        Private columnDocument_No As Global.System.Data.DataColumn
        
        Private columnDocument_Date As Global.System.Data.DataColumn
        
        Private columnPack_Complete_Date As Global.System.Data.DataColumn
        
        Private columnDelivery_Service As Global.System.Data.DataColumn
        
        Private columnShipping_Date As Global.System.Data.DataColumn
        
        Private columnDeparture_Time As Global.System.Data.DataColumn
        
        Private columnVender_Id As Global.System.Data.DataColumn
        
        Private columnVender As Global.System.Data.DataColumn
        
        Private columnVehicle As Global.System.Data.DataColumn
        
        Private columnPlate_No As Global.System.Data.DataColumn
        
        Private columnSeal_No As Global.System.Data.DataColumn
        
        Private columnCustomer_Shipping As Global.System.Data.DataColumn
        
        Private columnCustomer_Shipping_Location As Global.System.Data.DataColumn
        
        Private columnTransportRegion_ID As Global.System.Data.DataColumn
        
        Private columnTransportRegion As Global.System.Data.DataColumn
        
        Private columnPackSize As Global.System.Data.DataColumn
        
        Private columnQty As Global.System.Data.DataColumn
        
        Private columnCBM As Global.System.Data.DataColumn
        
        Private columnUnit As Global.System.Data.DataColumn
        
        Private columnuserName As Global.System.Data.DataColumn
        
        Private columnuser_id As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "VIEW_RPT_GoodsIssue_Delivery_Confirmation"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TransportManifest_IndexColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTransportManifest_Index
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Document_NoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDocument_No
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Document_DateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDocument_Date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Pack_Complete_DateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPack_Complete_Date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Delivery_ServiceColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDelivery_Service
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Shipping_DateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShipping_Date
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Departure_TimeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDeparture_Time
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Vender_IdColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVender_Id
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VenderColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVender
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property VehicleColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVehicle
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Plate_NoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPlate_No
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Seal_NoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSeal_No
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Customer_ShippingColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCustomer_Shipping
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Customer_Shipping_LocationColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCustomer_Shipping_Location
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TransportRegion_IDColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTransportRegion_ID
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TransportRegionColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTransportRegion
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PackSizeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPackSize
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property QtyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnQty
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CBMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCBM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property UnitColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnUnit
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property userNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnuserName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property user_idColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnuser_id
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
            Get
                Return CType(Me.Rows(index),VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
            End Get
        End Property
        
        Public Event VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChanging As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEventHandler
        
        Public Event VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChanged As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEventHandler
        
        Public Event VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeleting As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEventHandler
        
        Public Event VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeleted As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow(ByVal row As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow( _
                    ByVal TransportManifest_Index As String,  _
                    ByVal Document_No As String,  _
                    ByVal Document_Date As Date,  _
                    ByVal Pack_Complete_Date As Date,  _
                    ByVal Delivery_Service As String,  _
                    ByVal Shipping_Date As Date,  _
                    ByVal Departure_Time As Date,  _
                    ByVal Vender_Id As String,  _
                    ByVal Vender As String,  _
                    ByVal Vehicle As String,  _
                    ByVal Plate_No As String,  _
                    ByVal Seal_No As String,  _
                    ByVal Customer_Shipping As String,  _
                    ByVal Customer_Shipping_Location As String,  _
                    ByVal TransportRegion_ID As String,  _
                    ByVal TransportRegion As String,  _
                    ByVal PackSize As String,  _
                    ByVal Qty As Double,  _
                    ByVal CBM As Double,  _
                    ByVal Unit As String,  _
                    ByVal userName As String,  _
                    ByVal user_id As String) As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
            Dim rowVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow = CType(Me.NewRow,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
            Dim columnValuesArray() As Object = New Object() {TransportManifest_Index, Document_No, Document_Date, Pack_Complete_Date, Delivery_Service, Shipping_Date, Departure_Time, Vender_Id, Vender, Vehicle, Plate_No, Seal_No, Customer_Shipping, Customer_Shipping_Location, TransportRegion_ID, TransportRegion, PackSize, Qty, CBM, Unit, userName, user_id}
            rowVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
            Return rowVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable = CType(MyBase.Clone,VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnTransportManifest_Index = MyBase.Columns("TransportManifest_Index")
            Me.columnDocument_No = MyBase.Columns("Document_No")
            Me.columnDocument_Date = MyBase.Columns("Document_Date")
            Me.columnPack_Complete_Date = MyBase.Columns("Pack_Complete_Date")
            Me.columnDelivery_Service = MyBase.Columns("Delivery_Service")
            Me.columnShipping_Date = MyBase.Columns("Shipping_Date")
            Me.columnDeparture_Time = MyBase.Columns("Departure_Time")
            Me.columnVender_Id = MyBase.Columns("Vender_Id")
            Me.columnVender = MyBase.Columns("Vender")
            Me.columnVehicle = MyBase.Columns("Vehicle")
            Me.columnPlate_No = MyBase.Columns("Plate_No")
            Me.columnSeal_No = MyBase.Columns("Seal_No")
            Me.columnCustomer_Shipping = MyBase.Columns("Customer_Shipping")
            Me.columnCustomer_Shipping_Location = MyBase.Columns("Customer_Shipping_Location")
            Me.columnTransportRegion_ID = MyBase.Columns("TransportRegion_ID")
            Me.columnTransportRegion = MyBase.Columns("TransportRegion")
            Me.columnPackSize = MyBase.Columns("PackSize")
            Me.columnQty = MyBase.Columns("Qty")
            Me.columnCBM = MyBase.Columns("CBM")
            Me.columnUnit = MyBase.Columns("Unit")
            Me.columnuserName = MyBase.Columns("userName")
            Me.columnuser_id = MyBase.Columns("user_id")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnTransportManifest_Index = New Global.System.Data.DataColumn("TransportManifest_Index", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTransportManifest_Index)
            Me.columnDocument_No = New Global.System.Data.DataColumn("Document_No", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDocument_No)
            Me.columnDocument_Date = New Global.System.Data.DataColumn("Document_Date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDocument_Date)
            Me.columnPack_Complete_Date = New Global.System.Data.DataColumn("Pack_Complete_Date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPack_Complete_Date)
            Me.columnDelivery_Service = New Global.System.Data.DataColumn("Delivery_Service", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDelivery_Service)
            Me.columnShipping_Date = New Global.System.Data.DataColumn("Shipping_Date", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShipping_Date)
            Me.columnDeparture_Time = New Global.System.Data.DataColumn("Departure_Time", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDeparture_Time)
            Me.columnVender_Id = New Global.System.Data.DataColumn("Vender_Id", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVender_Id)
            Me.columnVender = New Global.System.Data.DataColumn("Vender", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVender)
            Me.columnVehicle = New Global.System.Data.DataColumn("Vehicle", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVehicle)
            Me.columnPlate_No = New Global.System.Data.DataColumn("Plate_No", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPlate_No)
            Me.columnSeal_No = New Global.System.Data.DataColumn("Seal_No", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSeal_No)
            Me.columnCustomer_Shipping = New Global.System.Data.DataColumn("Customer_Shipping", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCustomer_Shipping)
            Me.columnCustomer_Shipping_Location = New Global.System.Data.DataColumn("Customer_Shipping_Location", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCustomer_Shipping_Location)
            Me.columnTransportRegion_ID = New Global.System.Data.DataColumn("TransportRegion_ID", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTransportRegion_ID)
            Me.columnTransportRegion = New Global.System.Data.DataColumn("TransportRegion", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTransportRegion)
            Me.columnPackSize = New Global.System.Data.DataColumn("PackSize", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPackSize)
            Me.columnQty = New Global.System.Data.DataColumn("Qty", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnQty)
            Me.columnCBM = New Global.System.Data.DataColumn("CBM", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCBM)
            Me.columnUnit = New Global.System.Data.DataColumn("Unit", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnUnit)
            Me.columnuserName = New Global.System.Data.DataColumn("userName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnuserName)
            Me.columnuser_id = New Global.System.Data.DataColumn("user_id", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnuser_id)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow() As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
            Return CType(Me.NewRow,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangedEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChanged(Me, New VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent(CType(e.Row,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangingEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChanging(Me, New VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent(CType(e.Row,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeletedEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeleted(Me, New VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent(CType(e.Row,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeletingEvent) Is Nothing) Then
                RaiseEvent VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowDeleting(Me, New VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent(CType(e.Row,VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveVIEW_RPT_GoodsIssue_Delivery_ConfirmationRow(ByVal row As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsGoodsIssue_Delivery_Confirmation = New dsGoodsIssue_Delivery_Confirmation
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
        Inherits Global.System.Data.DataRow
        
        Private tableVIEW_RPT_GoodsIssue_Delivery_Confirmation As VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation = CType(Me.Table,VIEW_RPT_GoodsIssue_Delivery_ConfirmationDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TransportManifest_Index() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportManifest_IndexColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TransportManifest_Index' in table 'VIEW_RPT_GoodsIssue_Deli"& _ 
                            "very_Confirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportManifest_IndexColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Document_No() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_NoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Document_No' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirm"& _ 
                            "ation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_NoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Document_Date() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_DateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Document_Date' in table 'VIEW_RPT_GoodsIssue_Delivery_Confi"& _ 
                            "rmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_DateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Pack_Complete_Date() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Pack_Complete_DateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Pack_Complete_Date' in table 'VIEW_RPT_GoodsIssue_Delivery_"& _ 
                            "Confirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Pack_Complete_DateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Delivery_Service() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Delivery_ServiceColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Delivery_Service' in table 'VIEW_RPT_GoodsIssue_Delivery_Co"& _ 
                            "nfirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Delivery_ServiceColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Shipping_Date() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Shipping_DateColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Shipping_Date' in table 'VIEW_RPT_GoodsIssue_Delivery_Confi"& _ 
                            "rmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Shipping_DateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Departure_Time() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Departure_TimeColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Departure_Time' in table 'VIEW_RPT_GoodsIssue_Delivery_Conf"& _ 
                            "irmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Departure_TimeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Vender_Id() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Vender_IdColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Vender_Id' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmat"& _ 
                            "ion' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Vender_IdColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Vender() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VenderColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Vender' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmation"& _ 
                            "' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VenderColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Vehicle() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VehicleColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Vehicle' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmatio"& _ 
                            "n' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VehicleColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Plate_No() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Plate_NoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Plate_No' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmati"& _ 
                            "on' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Plate_NoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Seal_No() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Seal_NoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Seal_No' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmatio"& _ 
                            "n' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Seal_NoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Customer_Shipping() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_ShippingColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Customer_Shipping' in table 'VIEW_RPT_GoodsIssue_Delivery_C"& _ 
                            "onfirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_ShippingColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Customer_Shipping_Location() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_Shipping_LocationColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Customer_Shipping_Location' in table 'VIEW_RPT_GoodsIssue_D"& _ 
                            "elivery_Confirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_Shipping_LocationColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TransportRegion_ID() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegion_IDColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TransportRegion_ID' in table 'VIEW_RPT_GoodsIssue_Delivery_"& _ 
                            "Confirmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegion_IDColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property TransportRegion() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegionColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'TransportRegion' in table 'VIEW_RPT_GoodsIssue_Delivery_Con"& _ 
                            "firmation' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegionColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PackSize() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.PackSizeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PackSize' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmati"& _ 
                            "on' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.PackSizeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Qty() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.QtyColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Qty' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmation' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.QtyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CBM() As Double
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.CBMColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CBM' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmation' i"& _ 
                            "s DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.CBMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Unit() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.UnitColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Unit' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmation' "& _ 
                            "is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.UnitColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property userName() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.userNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'userName' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmati"& _ 
                            "on' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.userNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property user_id() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.user_idColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'user_id' in table 'VIEW_RPT_GoodsIssue_Delivery_Confirmatio"& _ 
                            "n' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.user_idColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTransportManifest_IndexNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportManifest_IndexColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTransportManifest_IndexNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportManifest_IndexColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDocument_NoNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_NoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDocument_NoNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_NoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDocument_DateNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_DateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDocument_DateNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Document_DateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPack_Complete_DateNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Pack_Complete_DateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPack_Complete_DateNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Pack_Complete_DateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDelivery_ServiceNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Delivery_ServiceColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDelivery_ServiceNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Delivery_ServiceColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShipping_DateNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Shipping_DateColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShipping_DateNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Shipping_DateColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDeparture_TimeNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Departure_TimeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDeparture_TimeNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Departure_TimeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVender_IdNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Vender_IdColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVender_IdNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Vender_IdColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVenderNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VenderColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVenderNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VenderColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsVehicleNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VehicleColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetVehicleNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.VehicleColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPlate_NoNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Plate_NoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPlate_NoNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Plate_NoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSeal_NoNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Seal_NoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSeal_NoNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Seal_NoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCustomer_ShippingNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_ShippingColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCustomer_ShippingNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_ShippingColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCustomer_Shipping_LocationNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_Shipping_LocationColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCustomer_Shipping_LocationNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.Customer_Shipping_LocationColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTransportRegion_IDNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegion_IDColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTransportRegion_IDNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegion_IDColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTransportRegionNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegionColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTransportRegionNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.TransportRegionColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPackSizeNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.PackSizeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPackSizeNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.PackSizeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsQtyNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.QtyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetQtyNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.QtyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCBMNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.CBMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCBMNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.CBMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsUnitNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.UnitColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetUnitNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.UnitColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsuserNameNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.userNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetuserNameNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.userNameColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isuser_idNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.user_idColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setuser_idNull()
            Me(Me.tableVIEW_RPT_GoodsIssue_Delivery_Confirmation.user_idColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class VIEW_RPT_GoodsIssue_Delivery_ConfirmationRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As VIEW_RPT_GoodsIssue_Delivery_ConfirmationRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
